---
- name: Install required packages
  apt:
    name: "{{ item }}"
  with_items:
    - curl
    - jq

- name: Create temporary file for my hostvars
  tempfile:
    suffix: .json
  register: tmp
  changed_when: false

- name: Write my hostvars to temporary file
  copy:
    content: "{{ hostvars[inventory_hostname] | to_json }}"
    dest: "{{ tmp.path }}"
  changed_when: false

- name: Configure zones
  script: >
    scripts/upsert-zone "{{ pdns_auth_api_connect | mandatory }}" "{{ pdns_auth_api_server }}" "{{ tmp.path }}" "{{ item }}"
  environment:
    apikey: "{{ pdns_auth_api_key }}"
  register: out
  changed_when: "'CHANGED' in out.stdout | default('')"
  with_items: "{{ pdns_auth_api_zones.keys() }}"

- name: Configure metadata for zones
  script: >
    scripts/upsert-domain-metadata "{{ pdns_auth_api_connect | mandatory }}" "{{ pdns_auth_api_server }}" "{{ tmp.path }}" "{{ item }}"
  environment:
    apikey: "{{ pdns_auth_api_key }}"
  register: out
  changed_when: "'CHANGED' in out.stdout | default('')"
  with_items: "{{ pdns_auth_api_zones.keys() }}"

- name: Upsert records in zones
  script: >
    scripts/upsert-records "{{ pdns_auth_api_connect | mandatory }}" "{{ pdns_auth_api_server }}" "{{ tmp.path }}" "{{ item }}"
  environment:
    apikey: "{{ pdns_auth_api_key }}"
  when: "pdns_auth_api_zones[item].kind | default('Master') == 'Master'"
  register: out
  changed_when: "'CHANGED' in out.stdout | default('')"
  with_items: "{{ pdns_auth_api_zones.keys() }}"

- name: Delete unknown zones
  script: >
    scripts/delete-zones "{{ pdns_auth_api_connect }}" "{{ pdns_auth_api_server }}" "{{ tmp.path }}"
  environment:
    apikey: "{{ pdns_auth_api_key }}"
  register: out
  changed_when: "'CHANGED' in out.stdout | default('')"
  when: pdns_auth_api_remove_unknown_zones

- name: Remove temporary file
  file:
    path: tmp.path
    state: absent
  changed_when: false
