---
- name: Update repositories cache (apt)
  apt:
    update_cache: yes
  changed_when: false
  when: ansible_pkg_mgr == "apt"

- name: Install required packages (apt)
  apt:
    name: "{{ item }}"
  with_items:
    - curl
    - jq
  when: ansible_pkg_mgr == "apt"

- name: Update repositories cache (pacman)
  pacman:
    update_cache: yes
  changed_when: false
  when: ansible_pkg_mgr == "pacman"

- name: Install required packages (pacman)
  pacman:
    name: "{{ item }}"
  with_items:
    - curl
    - jq
  when: ansible_pkg_mgr == "pacman"

- include_tasks: single-zone.yml
  with_items: "{{ pdns_auth_api_zones | mandatory }}"
  loop_control:
    loop_var: zone

- name: Delete unknown zones
  script: >
    scripts/delete-zones "{{ pdns_auth_api_connect }}" "{{ pdns_auth_api_server }}"
    "{{ pdns_auth_api_zones | map(attribute='name') | list | join(' ') }}"
  environment:
    apikey: "{{ pdns_auth_api_key }}"
  register: out
  changed_when: "'CHANGED' in out.stdout | default('')"
  when: pdns_auth_api_remove_unknown_zones
