#!/bin/bash

set -e
set -o pipefail
set -o nounset
umask 177

# Parameters
zone="${1}"
shift

changed=0
while IFS='' read -r currentline; do
	current="$(echo "${currentline}" | cut -d' ' -f1)"
	ok=0
	for param in "${@}"; do
		if [ "${current}" = "${param}" ]; then
			ok=1
			break
		fi
		if [ "${ok}" = 0 ]; then
			changed=1
			pdnsutil set-meta "${zone}" "${current}"
		fi
	done
done < <(pdnsutil get-meta "${zone}" | tail -n +2 | grep -v '^SOA-EDIT =' | grep -v '^SOA-EDIT-API =')

if [ "${changed}" = 1 ]; then
	echo CHANGED
fi
